#!/usr/bin/env python3
"""
fold.py — FCP reference fold tool (SPEC §7).

Folds an append-only events.jsonl into a human + machine readable state.md.
Applies audience gating: when a --destination is given, only events whose
`audience` permits that destination are included. With no destination, the
fold is owner-only (the private view) and excludes events tagged for other
audiences unless they also include "self"/"root".

This is a reference implementation, not the protocol. Keep it small and
auditable. Usage:

    fold.py event-stream/<source-id>/events.jsonl                 # private/owner view
    fold.py event-stream/<source-id>/events.jsonl -d mentorship      # gated for a destination
    fold.py event-stream/<source-id>/events.jsonl -d mentorship -o event-stream/<source-id>/state.md
"""
from __future__ import annotations
import argparse, json, sys
from collections import defaultdict
from datetime import datetime, timezone

OWNER_AUDIENCES = {"self", "root", "private"}


def load(path: str) -> list[dict]:
    events = []
    with open(path, encoding="utf-8") as f:
        for n, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue
            try:
                events.append(json.loads(line))
            except json.JSONDecodeError as e:
                sys.stderr.write(f"warning: skipping malformed line {n}: {e}\n")
    events.sort(key=lambda e: e.get("ts", ""))
    return events


def audiences_of(ev: dict) -> set[str]:
    a = ev.get("audience")
    if a is None:
        return set(OWNER_AUDIENCES)  # untagged => owner-only by default
    return {a} if isinstance(a, str) else set(a)


def permitted(ev: dict, destination: str | None) -> bool:
    auds = audiences_of(ev)
    if destination is None:
        # Private/owner view: include owner-tagged and untagged events only.
        return bool(auds & OWNER_AUDIENCES)
    return destination in auds or bool(auds & OWNER_AUDIENCES)


def fold(events: list[dict], destination: str | None) -> dict:
    """Materialise current state. Latest goal wins; other types accumulate."""
    kept = [e for e in events if permitted(e, destination)]
    state = {
        "current_goals": {},          # horizon -> latest goal text
        "recent": [],                  # chronological notable items
    }
    by_type = defaultdict(list)
    for e in kept:
        by_type[e.get("type", "unknown")].append(e)
    for e in by_type.get("goal.set", []):
        horizon = e["payload"].get("horizon", "open")
        state["current_goals"][horizon] = e["payload"].get("goal", "")
    for e in kept:
        if e.get("type") != "goal.set":
            state["recent"].append(e)
    return state, kept


def render(source: str, destination: str | None, state: dict, kept: list[dict]) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    last_ts = kept[-1]["ts"] if kept else "—"
    aud = destination or "self"
    fm = [
        "---",
        f"generated_from: events.jsonl",
        f"do_not_edit: true   # regenerated by fold.py; hand edits are lost",
        f"source: {source}",
        f"audience: {aud}",
        f"folded_at: {now}",
        f"latest_event: {last_ts}",
        f"event_count: {len(kept)}",
        "current_goals:",
    ]
    for horizon, goal in state["current_goals"].items() or [("", "")]:
        if goal:
            fm.append(f"  {horizon}: {json.dumps(goal)}")
    fm.append("---")

    body = [f"# Current state — {source}", "",
            f"*Folded view for audience `{aud}`. Source of truth is `events.jsonl`.*", ""]
    if state["current_goals"]:
        body.append("## Goals")
        for horizon, goal in state["current_goals"].items():
            if goal:
                body.append(f"- **{horizon}:** {goal}")
        body.append("")
    if state["recent"]:
        body.append("## Recent")
        for e in state["recent"][-20:]:
            t = e.get("type", "")
            p = e.get("payload", {})
            summary = p.get("note") or p.get("why") or p.get("event") or json.dumps(p)
            body.append(f"- `{e['ts'][:10]}` **{t}** — {summary}")
        body.append("")
    return "\n".join(fm + [""] + body) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description="Fold an FCP events.jsonl into state.md")
    ap.add_argument("events", help="path to events.jsonl")
    ap.add_argument("-d", "--destination", default=None,
                    help="destination audience to gate for (omit for private/owner view)")
    ap.add_argument("-o", "--out", default=None, help="output path (default: stdout)")
    args = ap.parse_args()

    events = load(args.events)
    source = events[0]["source"] if events else "unknown"
    state, kept = fold(events, args.destination)
    md = render(source, args.destination, state, kept)
    if args.out:
        with open(args.out, "w", encoding="utf-8") as f:
            f.write(md)
        sys.stderr.write(f"wrote {args.out} ({len(kept)} events, audience={args.destination or 'self'})\n")
    else:
        sys.stdout.write(md)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
